openapi: 3.0.3
info:
  title: ClientAPI - Analysis
  version: 1.0.0
servers:
  - url: https://
    description: Base URL for all API requests
paths:
  /v2/traffic/get_audience:
    post:
      tags:
      - Трафик V2
      summary: Get Audience
      operationId: get_audience_v2_traffic_get_audience_post
      security:
      - HTTPBearer: []
      parameters:
      - name: offset
        in: query
        required: false
        schema:
          type: integer
          description: Смещение
          default: 0
          title: Offset
        description: Смещение
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          maximum: 100
          exclusiveMinimum: 0
          description: Ограничение
          default: 50
          title: Limit
        description: Ограничение
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/application__api__traffic__schemas__AudienceRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Audience'
                title: Response Get Audience V2 Traffic Get Audience Post
        '401':
          description: Unauthorized
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    Audience:
      properties:
        user_id:
          type: integer
          title: User Id
        event_status_id:
          type: integer
          title: Event Status Id
        created_at:
          type: string
          format: date-time
          title: Created At
        is_premium:
          type: boolean
          title: Is Premium
        photo_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Photo Url
        first_name:
          anyOf:
          - type: string
          - type: 'null'
          title: First Name
        last_name:
          anyOf:
          - type: string
          - type: 'null'
          title: Last Name
        phone_number:
          anyOf:
          - type: string
          - type: 'null'
          title: Phone Number
        username:
          anyOf:
          - type: string
          - type: 'null'
          title: Username
        bio:
          anyOf:
          - type: string
          - type: 'null'
          title: Bio
        birthday:
          anyOf:
          - type: string
          - type: 'null'
          title: Birthday
        invite_link:
          anyOf:
          - type: string
          - type: 'null'
          title: Invite Link
        age:
          anyOf:
          - prefixItems:
            - type: integer
            - type: integer
            type: array
            maxItems: 2
            minItems: 2
          - type: 'null'
          title: Age
          readOnly: true
      type: object
      required:
      - user_id
      - event_status_id
      - created_at
      - is_premium
      - photo_url
      - first_name
      - last_name
      - phone_number
      - username
      - bio
      - birthday
      - invite_link
      - age
      title: Audience
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    application__api__traffic__schemas__AudienceRequest:
      properties:
        start_datetime:
          type: string
          format: date-time
          title: Start Datetime
          description: Дата и время начала периода
        end_datetime:
          type: string
          format: date-time
          title: End Datetime
          description: Дата и время окончания периода
        channel_id:
          type: integer
          title: Channel Id
          description: Идентификатор канала
        event_id:
          type: integer
          title: Event Id
          description: Идентификатор события
        invite_links_hash:
          items:
            anyOf:
            - type: string
            - type: 'null'
          type: array
          title: Invite Links Hash
          description: Хэши пригласительных ссылок
      type: object
      required:
      - start_datetime
      - end_datetime
      - channel_id
      - event_id
      title: AudienceRequest
