openapi: 3.0.3
info:
  title: ClientAPI - Analysis
  version: 1.0.0
servers:
  - url: https://
    description: Base URL for all API requests
paths:
  /v2/traffic/get_audience:
    get:
      tags:
        - Аудитория
      summary: Получить аудиторию канала
      description: Получение статистики по аудитории канала
      operationId: get_audience_v2_traffic_get_audience_get
      security:
        - HTTPBearer: []
      parameters:
        - name: channel_id
          in: query
          required: true
          schema:
            type: integer
          description: ID канала
        - name: start_datetime
          in: query
          required: true
          schema:
            type: string
            format: date-time
          description: Дата и время начала периода
        - name: end_datetime
          in: query
          required: true
          schema:
            type: string
            format: date-time
          description: Дата и время окончания периода
        - name: event_id
          in: query
          required: true
          schema:
            type: integer
          description: Идентификатор события (1 — подписка, 2 — отписка)
        - name: invite_links_hash
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
          description: Хэши пригласительных ссылок
        - name: is_premium
          in: query
          required: false
          schema:
            type: boolean
            nullable: true
          description: Фильтр премиум
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Номер страницы
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          description: Количество элементов на странице
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AudienceResponse"
        "422":
          description: Ошибка валидации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"

components:
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer

  schemas:
    AudienceResponse:
      type: object
      required:
        - total
        - page
        - limit
        - items
      properties:
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer
        items:
          type: array
          items:
            $ref: "#/components/schemas/AudienceItem"

    AudienceItem:
      type: object
      required:
        - user_id
        - username
        - is_premium
        - join_date
      properties:
        user_id:
          type: integer
        username:
          type: string
          nullable: true
        is_premium:
          type: boolean
        join_date:
          type: string
          format: date-time

    HTTPValidationError:
      type: object
      required:
        - detail
      properties:
        detail:
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"

    ValidationError:
      type: object
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          type: string
        type:
          type: string