openapi: 3.0.3
info:
  title: ClientAPI - Invite Links Endpoints
  version: 1.0.0
servers:
  - url: https://
    description: Base URL for all API requests
paths:
  /invite_links/{invite_link_id}:
    get:
      tags:
        - invite_links
      summary: Получить инвайт-ссылку по id
      description: Get invite link by id
      operationId: get_invite_link_invite_links__invite_link_id__get
      security:
        - HTTPBearer: []
      parameters:
        - name: invite_link_id
          in: path
          required: true
          schema:
            type: string
        - name: channel_id
          in: query
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InviteLinkResponseDTO"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
        "404":
          description: Invite link not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"

  /invite_links/all:
    post:
      tags:
        - invite_links
      summary: Получить все инвайт-ссылки с фильтрами
      description: Get all invite links with filters
      operationId: get_invite_links_invite_links_all_post
      security:
        - HTTPBearer: []
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
            description: Количество элементов на странице. При отрицательном значении пагинация отключается
        - name: channel_id
          in: query
          required: true
          schema:
            type: integer
        - name: name
          in: query
          required: false
          schema:
            type: string
            nullable: true
        - name: creator_id
          in: query
          required: false
          schema:
            type: integer
            nullable: true
        - name: ordered_fields
          in: query
          required: false
          schema:
            type: array
            items:
              $ref: "#/components/schemas/InviteLinksOrder"
            default: ["-created_at"]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Body_get_invite_links_invite_links_all_post"
        required: false
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AllInviteLinksResponseDTO"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"

  /invite_links:
    post:
      tags:
        - invite_links
      summary: Создать инвайт-ссылку
      description: Create invite link
      operationId: create_invite_link_invite_links_post
      security:
        - HTTPBearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InviteLinkCreateDTO"
      responses:
        "201":
          description: Успешно создано
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InviteLinkResponseDTO"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
        "403":
          description: Helper bot permissions exception
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
        "409":
          description: Bot not added to channel exception
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorSchema"
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"

components:
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer

  schemas:
    InviteLinkResponseDTO:
      type: object
      required:
        - id
        - channel_id
        - invite_link
        - creates_join_request
        - created_at
        - is_bot_created
        - budget
      properties:
        id:
          type: string
        name:
          type: string
          nullable: true
        channel_id:
          type: integer
        invite_link:
          type: string
        creates_join_request:
          type: boolean
        expire_date:
          type: string
          format: date-time
          nullable: true
        member_limit:
          type: integer
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
          nullable: true
        is_bot_created:
          type: boolean
        creator_id:
          type: integer
          nullable: true
        budget:
          type: number
        tags:
          type: array
          items:
            $ref: "#/components/schemas/TagInInviteLinkDTO"

    TagInInviteLinkDTO:
      type: object
      required:
        - id
        - name
        - color
        - type
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        color:
          type: string
        type:
          $ref: "#/components/schemas/TagTypeDTO"

    TagTypeDTO:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string

    InviteLinkCreateDTO:
      type: object
      required:
        - channel_id
        - name
      properties:
        channel_id:
          type: integer
        name:
          type: string
        creates_join_request:
          type: boolean
          default: false
        expire_date:
          type: string
          format: date-time
          nullable: true
        member_limit:
          type: integer
          nullable: true
        budget:
          type: number
          default: 0
        tags:
          type: array
          items:
            type: string
            format: uuid

    AllInviteLinksResponseDTO:
      type: object
      required:
        - page
        - limit
        - total
        - items
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        items:
          type: array
          items:
            $ref: "#/components/schemas/InviteLinkResponseDTO"

    Body_get_invite_links_invite_links_all_post:
      type: object
      properties:
        tags:
          type: array
          items:
            $ref: "#/components/schemas/TagsFiltering"
          nullable: true
          description: Фильтрация по тегам
        links_ids:
          type: array
          items:
            type: string
          nullable: true

    TagsFiltering:
      type: object
      required:
        - tag_type_id
        - tags
      properties:
        tag_type_id:
          type: string
          format: uuid
        without_type:
          type: boolean
          default: false
        tags:
          type: array
          items:
            type: string
            format: uuid

    InviteLinksOrder:
      type: string
      enum:
        - name
        - created_at
        - -name
        - -created_at

    ErrorSchema:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string

    HTTPValidationError:
      type: object
      required:
        - detail
      properties:
        detail:
          type: array
          items:
            $ref: "#/components/schemas/ValidationError"

    ValidationError:
      type: object
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          type: string
        type:
          type: string